/*
===============================================================================
PROJECT:
    Data Warehouse for Dairy Sheep Milk Production Analysis

FILE:
    scripts/01_schema_ddl.sql

PURPOSE:
    Create the dimensional model used by the BI project.

DATABASE:
    PostgreSQL / Amazon Aurora PostgreSQL

GRAIN:
    One row in sheep_dw.fact_milk_control represents one individual
    observation recorded in one physical row of the source sheet "Hoja1".

IMPORTANT:
    This script performs a clean rebuild of the sheep_dw and sheep_mart
    schemas. It deletes any existing objects inside those schemas.

EXECUTION ORDER:
    1. Run this DDL.
    2. Run the Python ETL.
    3. Run advanced SQL queries.
    4. Create analytical views for the dashboard.
===============================================================================
*/

BEGIN;

-- ============================================================================
-- 1. CLEAN REBUILD
-- ============================================================================

DROP SCHEMA IF EXISTS sheep_mart CASCADE;
DROP SCHEMA IF EXISTS sheep_dw CASCADE;

CREATE SCHEMA sheep_dw;
CREATE SCHEMA sheep_mart;

COMMENT ON SCHEMA sheep_dw IS
    'Atomic dimensional warehouse for dairy sheep milk-control observations.';

COMMENT ON SCHEMA sheep_mart IS
    'Analytical views and aggregated datasets consumed by the dashboard.';


-- ============================================================================
-- 2. DIMENSION: SHEEP
-- ============================================================================
-- One row per sheep.
--
-- sheep_key:
--     Surrogate key used by the fact table.
--
-- sheep_id:
--     Natural key from "Nº de Oveja" in Hoja1.
--
-- animal_code:
--     Anonymized code from column "O" in sheet CODIGOS ANIMALES.
-- ============================================================================

CREATE TABLE sheep_dw.dim_sheep (
    sheep_key      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sheep_id       BIGINT NOT NULL,
    animal_code    VARCHAR(20) NOT NULL,

    CONSTRAINT pk_dim_sheep
        PRIMARY KEY (sheep_key),

    CONSTRAINT uq_dim_sheep_sheep_id
        UNIQUE (sheep_id),

    CONSTRAINT uq_dim_sheep_animal_code
        UNIQUE (animal_code),

    CONSTRAINT ck_dim_sheep_positive_sheep_id
        CHECK (sheep_id > 0),

    CONSTRAINT ck_dim_sheep_nonempty_animal_code
        CHECK (BTRIM(animal_code) <> '')
);

COMMENT ON TABLE sheep_dw.dim_sheep IS
    'Relatively static identity of each sheep. Observation counts are derived from the fact table and are not stored here.';

COMMENT ON COLUMN sheep_dw.dim_sheep.sheep_key IS
    'Surrogate warehouse key.';

COMMENT ON COLUMN sheep_dw.dim_sheep.sheep_id IS
    'Natural sheep identifier from the source workbook.';

COMMENT ON COLUMN sheep_dw.dim_sheep.animal_code IS
    'Anonymized animal code from CODIGOS ANIMALES.';


-- ============================================================================
-- 3. DIMENSION: DATE
-- ============================================================================
-- Role-playing dimension used by:
--     fact_milk_control.control_date_key
--     fact_milk_control.lambing_date_key
--
-- date_key format:
--     YYYYMMDD as an integer.
--     Example: 20160310
-- ============================================================================

CREATE TABLE sheep_dw.dim_date (
    date_key        INTEGER NOT NULL,
    full_date       DATE NOT NULL,
    year            SMALLINT NOT NULL,
    quarter         SMALLINT NOT NULL,
    month           SMALLINT NOT NULL,
    month_name      VARCHAR(12) NOT NULL,
    week_of_year    SMALLINT NOT NULL,
    day_of_month    SMALLINT NOT NULL,
    day_of_year     SMALLINT NOT NULL,
    day_of_week     SMALLINT NOT NULL,
    day_name        VARCHAR(12) NOT NULL,
    is_weekend      BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_date
        PRIMARY KEY (date_key),

    CONSTRAINT uq_dim_date_full_date
        UNIQUE (full_date),

    CONSTRAINT ck_dim_date_year
        CHECK (year BETWEEN 1900 AND 2100),

    CONSTRAINT ck_dim_date_quarter
        CHECK (quarter BETWEEN 1 AND 4),

    CONSTRAINT ck_dim_date_month
        CHECK (month BETWEEN 1 AND 12),

    CONSTRAINT ck_dim_date_week
        CHECK (week_of_year BETWEEN 1 AND 53),

    CONSTRAINT ck_dim_date_day_of_month
        CHECK (day_of_month BETWEEN 1 AND 31),

    CONSTRAINT ck_dim_date_day_of_year
        CHECK (day_of_year BETWEEN 1 AND 366),

    CONSTRAINT ck_dim_date_day_of_week
        CHECK (day_of_week BETWEEN 1 AND 7),

    CONSTRAINT ck_dim_date_key_matches_date
        CHECK (
            date_key =
                EXTRACT(YEAR FROM full_date)::INTEGER * 10000
                + EXTRACT(MONTH FROM full_date)::INTEGER * 100
                + EXTRACT(DAY FROM full_date)::INTEGER
        )
);

COMMENT ON TABLE sheep_dw.dim_date IS
    'Role-playing calendar dimension used for control dates and lambing dates.';

COMMENT ON COLUMN sheep_dw.dim_date.date_key IS
    'Smart integer key in YYYYMMDD format.';

COMMENT ON COLUMN sheep_dw.dim_date.day_of_week IS
    'ISO day of week: Monday=1 and Sunday=7.';


-- ============================================================================
-- 4. DIMENSION: LACTATION STAGE
-- ============================================================================
-- Small static catalog.
--
-- It does not contain sheep_id or lambing_date.
-- Exact days in milk remain as a measure in the fact table.
--
-- The ranges are operational analytical groups, not causal or universal
-- biological definitions.
-- ============================================================================

CREATE TABLE sheep_dw.dim_lactation_stage (
    lactation_stage_key    SMALLINT NOT NULL,
    stage_code             VARCHAR(20) NOT NULL,
    stage_label            VARCHAR(60) NOT NULL,
    min_days_in_milk       INTEGER NOT NULL,
    max_days_in_milk       INTEGER,
    stage_order            SMALLINT NOT NULL,

    CONSTRAINT pk_dim_lactation_stage
        PRIMARY KEY (lactation_stage_key),

    CONSTRAINT uq_dim_lactation_stage_code
        UNIQUE (stage_code),

    CONSTRAINT uq_dim_lactation_stage_order
        UNIQUE (stage_order),

    CONSTRAINT ck_dim_lactation_stage_min_days
        CHECK (min_days_in_milk >= 0),

    CONSTRAINT ck_dim_lactation_stage_max_days
        CHECK (
            max_days_in_milk IS NULL
            OR max_days_in_milk >= min_days_in_milk
        ),

    CONSTRAINT ck_dim_lactation_stage_order
        CHECK (stage_order > 0),

    CONSTRAINT ck_dim_lactation_stage_nonempty_code
        CHECK (BTRIM(stage_code) <> ''),

    CONSTRAINT ck_dim_lactation_stage_nonempty_label
        CHECK (BTRIM(stage_label) <> '')
);

COMMENT ON TABLE sheep_dw.dim_lactation_stage IS
    'Static operational buckets used to analyze milk production by days in milk.';


-- Seed the static lactation-stage catalog.
INSERT INTO sheep_dw.dim_lactation_stage (
    lactation_stage_key,
    stage_code,
    stage_label,
    min_days_in_milk,
    max_days_in_milk,
    stage_order
)
VALUES
    (1, 'D000_030', '0-30 days',    0,   30, 1),
    (2, 'D031_060', '31-60 days',  31,   60, 2),
    (3, 'D061_090', '61-90 days',  61,   90, 3),
    (4, 'D091_120', '91-120 days', 91,  120, 4),
    (5, 'D121_180', '121-180 days',121,  180, 5),
    (6, 'D181_270', '181-270 days',181,  270, 6),
    (7, 'D271_365', '271-365 days',271,  365, 7),
    (8, 'D366_PLUS','366+ days',   366, NULL, 8);


-- ============================================================================
-- 5. DIMENSION: MANAGEMENT
-- ============================================================================
-- One row per unique combination of:
--     group_space_code + pen_id
--
-- Missing group space is represented as:
--     group_space_code  = -1
--     group_space_label = 'Unknown'
--
-- The original observation is preserved in the fact table.
-- ============================================================================

CREATE TABLE sheep_dw.dim_management (
    management_key         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    group_space_code       SMALLINT NOT NULL,
    group_space_label      VARCHAR(50) NOT NULL,
    pen_id                 SMALLINT NOT NULL,
    management_natural_key VARCHAR(80) NOT NULL,

    CONSTRAINT pk_dim_management
        PRIMARY KEY (management_key),

    CONSTRAINT uq_dim_management_natural_key
        UNIQUE (management_natural_key),

    CONSTRAINT uq_dim_management_business_values
        UNIQUE (group_space_code, pen_id),

    CONSTRAINT ck_dim_management_group_space
        CHECK (group_space_code >= -1),

    CONSTRAINT ck_dim_management_pen
        CHECK (pen_id > 0),

    CONSTRAINT ck_dim_management_nonempty_label
        CHECK (BTRIM(group_space_label) <> ''),

    CONSTRAINT ck_dim_management_nonempty_natural_key
        CHECK (BTRIM(management_natural_key) <> '')
);

COMMENT ON TABLE sheep_dw.dim_management IS
    'Management context defined by group-space code and pen identifier.';

COMMENT ON COLUMN sheep_dw.dim_management.management_natural_key IS
    'ETL-generated key such as space=2|pen=7.';


-- ============================================================================
-- 6. DIMENSION: WEATHER CONDITION
-- ============================================================================
-- Role-playing dimension used twice by the fact table:
--     current_weather_condition_key
--     previous_weather_condition_key
--
-- Continuous weather measurements remain in the fact table.
-- This dimension stores the categorical source classifications.
-- ============================================================================

CREATE TABLE sheep_dw.dim_weather_condition (
    weather_condition_key       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    wind_speed_category         SMALLINT NOT NULL,
    precipitation_category      SMALLINT NOT NULL,
    weather_natural_key         VARCHAR(80) NOT NULL,

    CONSTRAINT pk_dim_weather_condition
        PRIMARY KEY (weather_condition_key),

    CONSTRAINT uq_dim_weather_condition_natural_key
        UNIQUE (weather_natural_key),

    CONSTRAINT uq_dim_weather_condition_business_values
        UNIQUE (wind_speed_category, precipitation_category),

    CONSTRAINT ck_dim_weather_condition_wind_category
        CHECK (wind_speed_category >= 0),

    CONSTRAINT ck_dim_weather_condition_precipitation_category
        CHECK (precipitation_category >= 0),

    CONSTRAINT ck_dim_weather_condition_nonempty_key
        CHECK (BTRIM(weather_natural_key) <> '')
);

COMMENT ON TABLE sheep_dw.dim_weather_condition IS
    'Categorical weather classifications reused for the control day and previous day.';

COMMENT ON COLUMN sheep_dw.dim_weather_condition.weather_natural_key IS
    'ETL-generated key such as wind=2|precipitation=1.';


-- ============================================================================
-- 7. DIMENSION: LUNAR CONTEXT
-- ============================================================================
-- Role-playing dimension used twice by the fact table:
--     current_lunar_key
--     previous_lunar_key
-- ============================================================================

CREATE TABLE sheep_dw.dim_lunar (
    lunar_key          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    lunar_phase        VARCHAR(40) NOT NULL,
    lunar_phase_index  SMALLINT NOT NULL,
    lunar_natural_key  VARCHAR(80) NOT NULL,

    CONSTRAINT pk_dim_lunar
        PRIMARY KEY (lunar_key),

    CONSTRAINT uq_dim_lunar_natural_key
        UNIQUE (lunar_natural_key),

    CONSTRAINT uq_dim_lunar_business_values
        UNIQUE (lunar_phase, lunar_phase_index),

    CONSTRAINT ck_dim_lunar_phase_index
        CHECK (lunar_phase_index BETWEEN -31 AND 31),

    CONSTRAINT ck_dim_lunar_nonempty_phase
        CHECK (BTRIM(lunar_phase) <> ''),

    CONSTRAINT ck_dim_lunar_nonempty_key
        CHECK (BTRIM(lunar_natural_key) <> '')
);

COMMENT ON TABLE sheep_dw.dim_lunar IS
    'Lunar context reused for the control day and previous day.';

COMMENT ON COLUMN sheep_dw.dim_lunar.lunar_natural_key IS
    'ETL-generated key such as phase=Full Moon|index=3.';


-- ============================================================================
-- 8. DIMENSION: DATA QUALITY
-- ============================================================================
-- Small static catalog.
--
-- Invalid records that break required business rules will not be silently
-- categorized here: the ETL will fail or reject them.
--
-- This dimension is used for valid but incomplete source observations.
-- ============================================================================

CREATE TABLE sheep_dw.dim_data_quality (
    data_quality_key          SMALLINT NOT NULL,
    quality_code              VARCHAR(40) NOT NULL,
    quality_label             VARCHAR(100) NOT NULL,
    has_missing_group_space   BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_data_quality
        PRIMARY KEY (data_quality_key),

    CONSTRAINT uq_dim_data_quality_code
        UNIQUE (quality_code),

    CONSTRAINT ck_dim_data_quality_nonempty_code
        CHECK (BTRIM(quality_code) <> ''),

    CONSTRAINT ck_dim_data_quality_nonempty_label
        CHECK (BTRIM(quality_label) <> '')
);

COMMENT ON TABLE sheep_dw.dim_data_quality IS
    'Static catalog that communicates completeness of otherwise valid source observations.';


INSERT INTO sheep_dw.dim_data_quality (
    data_quality_key,
    quality_code,
    quality_label,
    has_missing_group_space
)
VALUES
    (1, 'COMPLETE', 'Complete source observation', FALSE),
    (2, 'MISSING_GROUP_SPACE', 'Group-space value missing in source', TRUE);


-- ============================================================================
-- 9. FACT TABLE: MILK CONTROL
-- ============================================================================
-- GRAIN:
-- One source observation recorded in one physical row of Hoja1.
--
-- source_row_number:
-- Physical Excel row number, including the header offset.
-- It provides source-level traceability and prevents duplicate loading.
--
-- Role-playing foreign keys:
--     control_date_key / lambing_date_key
--     current_weather_condition_key / previous_weather_condition_key
--     current_lunar_key / previous_lunar_key
-- ============================================================================

CREATE TABLE sheep_dw.fact_milk_control (
    milk_control_key                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_row_number                 INTEGER NOT NULL,

    sheep_key                         INTEGER NOT NULL,
    control_date_key                  INTEGER NOT NULL,
    lambing_date_key                  INTEGER NOT NULL,
    lactation_stage_key               SMALLINT NOT NULL,
    management_key                    INTEGER NOT NULL,

    current_weather_condition_key     INTEGER NOT NULL,
    previous_weather_condition_key    INTEGER NOT NULL,

    current_lunar_key                 INTEGER NOT NULL,
    previous_lunar_key                INTEGER NOT NULL,

    data_quality_key                  SMALLINT NOT NULL,

    -- Production measures
    morning_milking_liters            NUMERIC(10,4) NOT NULL,
    afternoon_milking_liters          NUMERIC(10,4) NOT NULL,
    total_milk_liters                 NUMERIC(10,4) NOT NULL,
    days_in_milk                      INTEGER NOT NULL,

    -- Weather measures: control day
    avg_temp_c                        NUMERIC(10,4) NOT NULL,
    max_temp_c                        NUMERIC(10,4) NOT NULL,
    min_temp_c                        NUMERIC(10,4) NOT NULL,

    avg_humidity_pct                  NUMERIC(10,4) NOT NULL,
    max_humidity_pct                  NUMERIC(10,4) NOT NULL,
    min_humidity_pct                  NUMERIC(10,4) NOT NULL,

    thi                               NUMERIC(10,4) NOT NULL,

    wind_speed_mps                    NUMERIC(10,4) NOT NULL,
    wind_direction_deg                NUMERIC(10,4) NOT NULL,
    max_wind_speed_mps                NUMERIC(10,4) NOT NULL,
    max_wind_direction_deg            NUMERIC(10,4) NOT NULL,

    radiation_mj_m2                   NUMERIC(10,4) NOT NULL,
    precipitation_mm                  NUMERIC(10,4) NOT NULL,

    -- Weather measures: previous day
    avg_temp_c_previous_day           NUMERIC(10,4) NOT NULL,
    max_temp_c_previous_day           NUMERIC(10,4) NOT NULL,
    min_temp_c_previous_day           NUMERIC(10,4) NOT NULL,

    avg_humidity_pct_previous_day     NUMERIC(10,4) NOT NULL,
    max_humidity_pct_previous_day     NUMERIC(10,4) NOT NULL,
    min_humidity_pct_previous_day     NUMERIC(10,4) NOT NULL,

    thi_previous_day                  NUMERIC(10,4) NOT NULL,

    wind_speed_mps_previous_day       NUMERIC(10,4) NOT NULL,
    wind_direction_deg_previous_day   NUMERIC(10,4) NOT NULL,
    max_wind_speed_mps_previous_day   NUMERIC(10,4) NOT NULL,
    max_wind_direction_deg_previous_day NUMERIC(10,4) NOT NULL,

    radiation_mj_m2_previous_day      NUMERIC(10,4) NOT NULL,
    precipitation_mm_previous_day     NUMERIC(10,4) NOT NULL,

    CONSTRAINT pk_fact_milk_control
        PRIMARY KEY (milk_control_key),

    CONSTRAINT uq_fact_milk_control_source_row
        UNIQUE (source_row_number),

    CONSTRAINT fk_fact_milk_control_sheep
        FOREIGN KEY (sheep_key)
        REFERENCES sheep_dw.dim_sheep (sheep_key),

    CONSTRAINT fk_fact_milk_control_control_date
        FOREIGN KEY (control_date_key)
        REFERENCES sheep_dw.dim_date (date_key),

    CONSTRAINT fk_fact_milk_control_lambing_date
        FOREIGN KEY (lambing_date_key)
        REFERENCES sheep_dw.dim_date (date_key),

    CONSTRAINT fk_fact_milk_control_lactation_stage
        FOREIGN KEY (lactation_stage_key)
        REFERENCES sheep_dw.dim_lactation_stage (lactation_stage_key),

    CONSTRAINT fk_fact_milk_control_management
        FOREIGN KEY (management_key)
        REFERENCES sheep_dw.dim_management (management_key),

    CONSTRAINT fk_fact_milk_control_current_weather
        FOREIGN KEY (current_weather_condition_key)
        REFERENCES sheep_dw.dim_weather_condition (weather_condition_key),

    CONSTRAINT fk_fact_milk_control_previous_weather
        FOREIGN KEY (previous_weather_condition_key)
        REFERENCES sheep_dw.dim_weather_condition (weather_condition_key),

    CONSTRAINT fk_fact_milk_control_current_lunar
        FOREIGN KEY (current_lunar_key)
        REFERENCES sheep_dw.dim_lunar (lunar_key),

    CONSTRAINT fk_fact_milk_control_previous_lunar
        FOREIGN KEY (previous_lunar_key)
        REFERENCES sheep_dw.dim_lunar (lunar_key),

    CONSTRAINT fk_fact_milk_control_data_quality
        FOREIGN KEY (data_quality_key)
        REFERENCES sheep_dw.dim_data_quality (data_quality_key),

    CONSTRAINT ck_fact_milk_control_source_row
        CHECK (source_row_number >= 2),

    CONSTRAINT ck_fact_milk_control_morning_milk
        CHECK (morning_milking_liters >= 0),

    CONSTRAINT ck_fact_milk_control_afternoon_milk
        CHECK (afternoon_milking_liters >= 0),

    CONSTRAINT ck_fact_milk_control_total_milk
        CHECK (total_milk_liters >= 0),

    CONSTRAINT ck_fact_milk_control_milk_balance
        CHECK (
            ABS(
                total_milk_liters
                - morning_milking_liters
                - afternoon_milking_liters
            ) <= 0.0100
        ),

    CONSTRAINT ck_fact_milk_control_days_in_milk
        CHECK (days_in_milk >= 0),

    CONSTRAINT ck_fact_milk_control_avg_humidity
        CHECK (avg_humidity_pct BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_max_humidity
        CHECK (max_humidity_pct BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_min_humidity
        CHECK (min_humidity_pct BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_avg_humidity_previous
        CHECK (avg_humidity_pct_previous_day BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_max_humidity_previous
        CHECK (max_humidity_pct_previous_day BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_min_humidity_previous
        CHECK (min_humidity_pct_previous_day BETWEEN 0 AND 100),

    CONSTRAINT ck_fact_milk_control_wind_speed
        CHECK (wind_speed_mps >= 0),

    CONSTRAINT ck_fact_milk_control_max_wind_speed
        CHECK (max_wind_speed_mps >= 0),

    CONSTRAINT ck_fact_milk_control_wind_speed_previous
        CHECK (wind_speed_mps_previous_day >= 0),

    CONSTRAINT ck_fact_milk_control_max_wind_speed_previous
        CHECK (max_wind_speed_mps_previous_day >= 0),

    CONSTRAINT ck_fact_milk_control_wind_direction
        CHECK (wind_direction_deg BETWEEN 0 AND 360),

    CONSTRAINT ck_fact_milk_control_max_wind_direction
        CHECK (max_wind_direction_deg BETWEEN 0 AND 360),

    CONSTRAINT ck_fact_milk_control_wind_direction_previous
        CHECK (wind_direction_deg_previous_day BETWEEN 0 AND 360),

    CONSTRAINT ck_fact_milk_control_max_wind_direction_previous
        CHECK (max_wind_direction_deg_previous_day BETWEEN 0 AND 360),

    CONSTRAINT ck_fact_milk_control_radiation
        CHECK (radiation_mj_m2 >= 0),

    CONSTRAINT ck_fact_milk_control_radiation_previous
        CHECK (radiation_mj_m2_previous_day >= 0),

    CONSTRAINT ck_fact_milk_control_precipitation
        CHECK (precipitation_mm >= 0),

    CONSTRAINT ck_fact_milk_control_precipitation_previous
        CHECK (precipitation_mm_previous_day >= 0)
);

COMMENT ON TABLE sheep_dw.fact_milk_control IS
    'Atomic fact table: one row per physical observation in Hoja1.';

COMMENT ON COLUMN sheep_dw.fact_milk_control.milk_control_key IS
    'Surrogate fact-table key.';

COMMENT ON COLUMN sheep_dw.fact_milk_control.source_row_number IS
    'Physical row number in Hoja1, used for source traceability and ETL idempotency.';

COMMENT ON COLUMN sheep_dw.fact_milk_control.control_date_key IS
    'Role-playing FK to dim_date for the milk-control date.';

COMMENT ON COLUMN sheep_dw.fact_milk_control.lambing_date_key IS
    'Role-playing FK to dim_date for the lambing date.';

COMMENT ON COLUMN sheep_dw.fact_milk_control.days_in_milk IS
    'Exact number of elapsed days between lambing date and control date.';


-- ============================================================================
-- 10. INDEXES
-- ============================================================================
-- PostgreSQL automatically creates indexes for:
--     primary keys
--     unique constraints
--
-- It does not automatically create indexes for foreign keys.
-- These indexes support joins and the main dashboard filters.
-- ============================================================================

CREATE INDEX idx_fact_milk_control_sheep_date
    ON sheep_dw.fact_milk_control (
        sheep_key,
        control_date_key
    );

CREATE INDEX idx_fact_milk_control_control_date
    ON sheep_dw.fact_milk_control (
        control_date_key
    );

CREATE INDEX idx_fact_milk_control_lambing_date
    ON sheep_dw.fact_milk_control (
        lambing_date_key
    );

CREATE INDEX idx_fact_milk_control_lactation_stage
    ON sheep_dw.fact_milk_control (
        lactation_stage_key
    );

CREATE INDEX idx_fact_milk_control_management
    ON sheep_dw.fact_milk_control (
        management_key
    );

CREATE INDEX idx_fact_milk_control_current_weather
    ON sheep_dw.fact_milk_control (
        current_weather_condition_key
    );

CREATE INDEX idx_fact_milk_control_previous_weather
    ON sheep_dw.fact_milk_control (
        previous_weather_condition_key
    );

CREATE INDEX idx_fact_milk_control_current_lunar
    ON sheep_dw.fact_milk_control (
        current_lunar_key
    );

CREATE INDEX idx_fact_milk_control_previous_lunar
    ON sheep_dw.fact_milk_control (
        previous_lunar_key
    );

CREATE INDEX idx_fact_milk_control_quality
    ON sheep_dw.fact_milk_control (
        data_quality_key
    );

CREATE INDEX idx_dim_management_pen
    ON sheep_dw.dim_management (
        pen_id
    );

CREATE INDEX idx_dim_management_group_space
    ON sheep_dw.dim_management (
        group_space_code
    );


COMMIT;


/*
===============================================================================
POST-DEPLOYMENT VERIFICATION QUERIES

Run these after executing the file.
===============================================================================

-- 1. Schemas
SELECT schema_name
FROM information_schema.schemata
WHERE schema_name IN ('sheep_dw', 'sheep_mart')
ORDER BY schema_name;


-- 2. Warehouse tables
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema IN ('sheep_dw', 'sheep_mart')
  AND table_type = 'BASE TABLE'
ORDER BY table_schema, table_name;


-- 3. Seeded lactation stages
SELECT *
FROM sheep_dw.dim_lactation_stage
ORDER BY stage_order;


-- 4. Seeded quality categories
SELECT *
FROM sheep_dw.dim_data_quality
ORDER BY data_quality_key;


-- 5. Foreign keys on the fact table
SELECT
    tc.constraint_name,
    kcu.column_name,
    ccu.table_schema AS referenced_schema,
    ccu.table_name AS referenced_table,
    ccu.column_name AS referenced_column
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.constraint_schema = kcu.constraint_schema
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
   AND ccu.constraint_schema = tc.constraint_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'sheep_dw'
  AND tc.table_name = 'fact_milk_control'
ORDER BY kcu.ordinal_position;


-- 6. Tables should still be empty before ETL
SELECT COUNT(*) AS fact_rows
FROM sheep_dw.fact_milk_control;

*/
